apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.namespace | default 'mysql-staging' }}
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
  clusterIP: None