apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: {{ .Values.namespace | default 'mysql-staging' }}
type: Opaque
data:
  {{- range $k, $v := .Values.configs }}
  {{ $k }}: {{ $v | toString | b64enc | quote }}
  {{- end }}
