apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.commmon.namespace | default .Release.Namespace }}
type: Opaque
data:
{{- range $k, $v := .Values.kube2py.secrets }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
