apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.commmon.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP