apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mate-ingress
  namespace: {{ .Values.commmon.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /(|$)(.*)
        backend:
          service:
            name: {{ .Chart.Name }}-service
            port:
              number: 80