name: python-deployment
run-name: ${{ github.actor }} - ${{ github.ref_name }}


on:
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PYTHON_VERSION: 3.8
  DockerImageName: kube2py


jobs:
  python-ci:
    name: Python CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Setup Python ${{ env.PYTHON_VERSION}}
        with:
          python-version: '${{ env.PYTHON_VERSION}}'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install -r requirements.txt

      - name: Lint
        run: |
          cd ../
          flake8 . --show-source --statistics

      - name: Check Complexity
        run: |
          cd ../
          flake8 . --statistics --max-complexity=10 --exit-zero

      - name: Run unit test with pytest
        run: |
          pytest -v --cov=. --cov-report=json

      - name: Upload Artifacts
        if: github.ref_name == 'main'
        uses: actions/upload-artifact@v4
        with:
          name: python-artifact
          path: .



  build-image:
    name: Build and Push Image
    needs: ['python-ci']
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-artifact
          path: .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./src
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DockerImageName }}:${{ github.sha }}

